# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PASB Bank DEV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PASB Bank DEV

  target 'PASB Bank DEVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PASB Bank DEVUITests' do
    # Pods for testing
  end

end
