version: 2.1

jobs:
  build:
    macos:
      xcode: "15.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            xcodebuild -resolvePackageDependencies
            xcodebuild -scheme StaticDemoApp -workspace StaticDemoApp.xcworkspace -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro' clean build
      - run:
          name: Run Tests
          command: |
            xcodebuild -scheme StaticDemoApp -workspace StaticDemoApp.xcworkspace -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro' test

  deploy:
    macos:
      xcode: "15.0"
    steps:
      - checkout
      - run:
          name: Deploy to TestFlight
          command: |
            # Add your deployment steps here

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

